# Preprocessing Techniques

### Import some packages

In [1]:
import numpy as np
from sklearn import preprocessingocessing

/home/folafunmi/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
input_data = np.array([[5.1, -2.9, 3.3], 
                       [-1.2, 7.8, -6.1], 
                       [3.9, 0.4, 2.1], 
                       [7.3, -9.9, -4.5]]) 

## Types of preprocessing techniques

### 1. Binarization
This process is used when we want to convert our numerical values into boolean values.
Using 2.1 as the threshold, all values above it would become 1 and the rest becomes 0.

In [3]:
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
